# command_timeout = 100
format = "[$all](dimmed white)"

[aws]
symbol = "  "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
style = "italic white"
read_only = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "
style = "bold white"

[git_status]
style = "bold yellow"
format = '([$all_status$ahead_behind]($style) )'
ahead = "↑"
behind = "↓"
staged = "＋"

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[memory_usage]
symbol = " "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[package]
symbol = " "
style = "dimmed yellow"

[perl]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[shlvl]
symbol = " "

[swift]
symbol = "ﯣ "

[character]
success_symbol = "[❯](dimmed green)"
error_symbol = "[❯](dimmed red)"

[jobs]
disabled = true
